---
- name: Download chromedriver.
  unarchive:
    remote_src: yes
    src: https://github.com/electron/electron/releases/download/v7.1.1/chromedriver-v7.1.1-linux-arm64.zip
    dest: /usr/local/bin
  become: yes
- name: Setup chromedriver.
  file:
    path: /usr/local/bin/chromedriver
    mode: +x
  become: yes
