services:
  chrome:
    image: &chrome_image docker.io/videomark/chrome:latest
    build:
      context: chrome
      # args:
      #   extension_url: https://sodium-extension.netlify.com/
    init: true
  sodium-bot:
    image: docker.io/videomark/sodium-bot:${VERSION:-latest}
    build:
      context: "."
      args:
        from: *chrome_image
    depends_on:
      - chrome
    ipc: host
    # ports:
    #   - "8080:8080"
    # environment:
    #   DEBUG: "*"
    # volumes:
    #   - ".:/app"
