version: "3"
services:
  chrome:
    build:
      context: chrome
      # args:
      #   extension_url: https://sodium-extension.netlify.com/
    environment:
      PORT: "8008"
    ports:
      - "8008:8008"
    shm_size: 256M
  bot:
    build: "."
    depends_on:
      - chrome
    environment:
      SELENIUM_REMOTE_URL: http://chrome:8008
      VIDEOMARK_EXTENSION_PATH: videomark-extension
      SESSION_ID: sodium
      # BROWSER: chrome
      # DEBUG: "*"
    volumes:
      - ".:/app"
