version: "3"
services:
  chrome:
    image: &chrome_image docker.io/videomark/chrome:latest
    build:
      context: chrome
      # args:
      #   extension_url: https://sodium-extension.netlify.com/
  app:
    image: &image docker.io/videomark/sodium-bot:${VERSION}
    build:
      context: "."
      args:
        from: *chrome_image
        session_id: *image
    depends_on:
      - chrome
    # environment:
    #   DEBUG: "*"
    volumes:
      - ".:/app"
    shm_size: 256M
