version: "3"
services:
  chromium:
    build:
      context: chromium
      # args:
      #   extension_url: https://sodium-extension.netlify.com/
    environment:
      PORT: "8008"
    ports:
      - "8008:8008"
    shm_size: 256m
  bot:
    build: "."
    depends_on:
      - chromium
    environment:
      SELENIUM_REMOTE_URL: http://chromium:8008
      VIDEOMARK_EXTENSION_PATH: videomark-extension
      SESSION_ID: sodium
    volumes:
      - ".:/app"
