---
- hosts: localhost
  tasks:
    - cron:
        env: yes
        # state: absent
        name: PATH
        value: "{{ ansible_env.PATH }}"
    - cron:
        name: ansible-pull
        # state: absent
        minute: "*/5"
        job: >
          ansible-pull
          --only-if-changed
          --url git@github.com:videomark/sodium-bot.git
          playbook.yml
    - file:
        state: absent
        path: "{{ ansible_env.HOME }}/videomark-extension"
    - file:
        state: directory
        path: "{{ ansible_env.HOME }}/videomark-extension"
    - unarchive:
        remote_src: yes
        src: https://sodium-extension.netlify.com/
        dest: "{{ ansible_env.HOME }}/videomark-extension"
    - cron:
        env: yes
        # state: absent
        name: VIDEOMARK_EXTENSION_PATH
        value: "{{ ansible_env.HOME }}/videomark-extension"
    - cron:
        name: chromedriver
        # state: absent
        special_time: reboot
        job: >
          while sleep 1; do
          DISPLAY=:0 chromedriver --port=8008;
          done
    - cron:
        env: yes
        # state: absent
        name: SELENIUM_REMOTE_URL
        value: http://localhost:8008
    - cron:
        env: yes
        # state: absent
        name: SESSION_ID
        value: sodium
    - npm:
        path: sodium-bot
        ci: yes
    - cron:
        name: sodium-bot
        # state: absent
        special_time: reboot
        job: >
          while sleep 1; do
          pkill ^chromium || true
          rm -rf /tmp/.org.chromium.Chromium.*
          npm --prefix "{{ ansible_env.PWD }}" start;
          done >> "{{ ansible_env.HOME }}"/sodium-bot.log 2>&1
    - shell: sudo reboot
