---
- hosts: localhost
  tasks:
    - cron:
        env: yes
        # state: absent
        name: PATH
        value: "{{ ansible_env.PATH }}"
    - cron:
        name: ansible-pull
        # state: absent
        minute: "*/5"
        job: >
          ansible-pull
          --only-if-changed
          --url git@github.com:webdino/sodium.git
          sodium-bot/playbook.yml
    - file:
        state: absent
        path: "{{ ansible_env.HOME }}/videomark-extension"
    - file:
        state: directory
        path: "{{ ansible_env.HOME }}/videomark-extension"
    - unarchive:
        remote_src: yes
        src: https://sodium-extension.netlify.com/
        dest: "{{ ansible_env.HOME }}/videomark-extension"
    - cron:
        env: yes
        # state: absent
        name: VIDEOMARK_EXTENSION_PATH
        value: "{{ ansible_env.HOME }}/videomark-extension"
    - shell: pkill chromium-browser
      ignore_errors: yes
    - shell: pkill chromedriver
      ignore_errors: yes
    - cron:
        name: chromedriver
        # state: absent
        special_time: reboot
        job: DISPLAY=:0 chromedriver --port=8008
    - shell: DISPLAY=:0 nohup chromedriver --port=8008 &
    - cron:
        env: yes
        # state: absent
        name: SELENIUM_REMOTE_URL
        value: http://localhost:8008
    - cron:
        env: yes
        # state: absent
        name: SESSION_ID
        value: sodium
    - npm:
        path: sodium-bot
        ci: yes
    - cron:
        name: sodium-bot
        # state: absent
        minute: "*/5"
        job: >
          cd -- "{{ ansible_env.PWD }}";
          test -f session.json && npm run down;
          npm start >> "{{ ansible_env.HOME }}"/sodium-bot.log 2>&1
