---
- name: Download get-pip.py.
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp
- name: Execute get-pip.py.
  command: python /tmp/get-pip.py
  become: yes
- name: Delete get-pip.py.
  file:
    state: absent
    path: /tmp/get-pip.py
- name: Install build tools.
  apt:
    name:
      - build-essential
      - libffi-dev
      - libssl-dev
    update_cache: yes
    cache_valid_time: 86400
  become: yes
- name: Install Ansible.
  pip:
    name: ansible
  become: yes
