---
- name: Install gnupg.
  apt:
    name: gnupg
    update_cache: yes
    cache_valid_time: 86400
  become: yes
- name: Add Ansible apt key.
  apt_key:
    id: 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367
    keyserver: keyserver.ubuntu.com
- name: Install apt-transport-https.
  apt:
    name: apt-transport-https
    update_cache: yes
    cache_valid_time: 86400
  become: yes
- name: Add Ansible repositorie.
  apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
  become: yes
- name: Install Ansible.
  apt:
    name: ansible
    update_cache: yes
    cache_valid_time: 86400
  become: yes
