---
- name: Install Ansible.
  import_tasks: ansible-debian.yml
  when:
    - ansible_os_family == "Debian"
    - ansible_architecture == "x86_64"
- name: Install Ansible.
  import_tasks: ansible-debian-aarch64.yml
  when:
    - ansible_os_family == "Debian"
    - ansible_architecture == "aarch64"
