---
- name: Install gnupg.
  apt:
    name: gnupg
    update_cache: yes
    cache_valid_time: 86400
  become: yes
- name: Add NodeSource apt key.
  apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- name: Install apt-transport-https.
  apt:
    name: apt-transport-https
    update_cache: yes
    cache_valid_time: 86400
  become: yes
- name: Add NodeSource repositories.
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
  become: yes
- name: Install Node.js.
  apt:
    name: nodejs
    update_cache: yes
    cache_valid_time: 86400
  become: yes
