name: Docker
on:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      - name: Set the VERSION
        run: echo "::set-env name=VERSION::${GITHUB_REF##*/}"
        if: github.ref != 'refs/heads/master'
      - run: docker-compose build
      - run: docker-compose push
