name: Docker
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /var/lib/docker
          key: docker
      - run: >
        echo '${{ secrets.DOCKER_PASSWORD }}' |
        docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      - run: docker-compose build
      - run: docker-compose push
