name: Docker
on: push
jobs:
  docker-push:
    runs-on: ubuntu-latest
    env:
      VERSION: latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /var/lib/docker
          key: docker
      - run: docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_PASSWORD }}'
      - run: docker-compose build
      - run: docker-compose push
